### ISSUE TITLE
Test failure on Windows

### ISSUE THREAD

**Issue by peterneubauer** [neo4j-contrib/graph-collections#9]
Hi there,

http://builder.neo4j.org/viewLog.html?buildId=42676&buildTypeId=bt164&tab=buildLog is failing on Windows with

junit.framework.AssertionFailedError
    at junit.framework.Assert.fail(Assert.java:48)
    at junit.framework.Assert.assertTrue(Assert.java:20)
    at junit.framework.Assert.assertTrue(Assert.java:27)
    at org.neo4j.collections.list.TestUnrolledLinkedListConcurrency.testAddInSamePageHavingReadPastWithoutReadTransaction(TestUnrolledLinkedListConcurrency.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
[14:15:56]: [org.neo4j:neo4j-graph-collections] There are test failures.

Please refer to C:\BuildAgent\work\3696941add7e2669\target\surefire-reports for the individual test results.
[14:15:56]: [ERROR] BUILD FAILURE
[14:15:56]: Process exited with code 1
[14:15:57]: Build finished

You can log in as guest to see it ...

Any clue what is happening?

**Comment by AndreasWilhelm** [comment]
Hi,

hm bei mir baut er durch, wrde jetzt darauf tippen das ein test vielleicht
vorher mal schief gegangen ist und dieser den neuen Build behindert hat. Hab
ich auch fters wenn ich einen build abbreche, jedoch AssertionFailedError
deutet eigentlich auf ein anderes Problem hin. Hab leider keine Idee.

Viele Gre

Andreas

2011/10/5 Peter Neubauer <
reply@reply.github.com>

**Comment by simpsonjulian** [comment]
Hi,

That's odd.  All I can think of is:
- different JVM version on the windows node
- platform-specific bug in the windows JVM

I can fire up a windows AWS node if you want to test it there ...

J.

On 5 October 2011 14:58, Peter Neubauer <
reply@reply.github.com>wrote:

> Hi there,
> 
> http://builder.neo4j.org/viewLog.html?buildId=42676&buildTypeId=bt164&tab=buildLogis failing on Windows with
> 
> [14:15:49]: [testAddInSamePageHavingReadPastWithoutReadTransaction]
> junit.framework.AssertionFailedError
>        at junit.framework.Assert.fail(Assert.java:48)
>        at junit.framework.Assert.assertTrue(Assert.java:20)
>        at junit.framework.Assert.assertTrue(Assert.java:27)
>        at
> org.neo4j.collections.list.TestUnrolledLinkedListConcurrency.testAddInSamePageHavingReadPastWithoutReadTransaction(TestUnrolledLinkedListConcurrency.java:158)
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>        at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>        at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>        at java.lang.reflect.Method.invoke(Method.java:597)
>        at
> org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
>        at
> org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
>        at
> org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
>        at
> org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
>        at
> org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
>        at
> org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
>        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
>        at
> org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
>        at
> org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
>        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
>        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
>        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
>        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
>        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
>        at
> org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
>        at
> org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
>        at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
>        at
> org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
>        at
> org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
>        at
> org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>        at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>        at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>        at java.lang.reflect.Method.invoke(Method.java:597)
>        at
> org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
>        at
> org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
>        at
> org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
>        at
> org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104)
>        at
> org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
> [14:15:56]: [org.neo4j:neo4j-graph-collections] There are test failures.
> 
> Please refer to C:\BuildAgent\work\3696941add7e2669\target\surefire-reports
> for the individual test results.
> [14:15:56]: [ERROR] BUILD FAILURE
> [14:15:56]: Process exited with code 1
> [14:15:57]: Build finished
> 
> You can log in as guest to see it ...
> 
> Any clue what is happening?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/neo4j/graph-collections/issues/9

## 

Julian Simpson
The Build Doctor Ltd.
http://www.build-doctor.com
julian@build-doctor.com
(+44) 207 183 0323

**Comment by brycenz** [comment]
Hi,

Only just managed to look at this, already passing again I see (without any
changes).  I have had a look at the build history (particularly the duration
taken for this test).  Generally it is taking less than 100ms (mostly less
than 10ms).  The two failing executions of that test took just over 10s,
which is significant since the assertion that failed is waiting for a signal
from the reading thread up to a limit of 10s.

So either there was a lot more load on the test server at the time (seems
unlikely, looking at the other test timings on one of the failing builds
there was a little bit extra load), or there is a race condition that was
triggered by a small change in load (seems more likely based on what I see
in the timing graphs).

From looking back at:
https://github.com/neo4j/graph-collections/blob/master/src/test/java/org/neo4j/collections/list/TestUnrolledLinkedListConcurrency.javahttps://github.com/neo4j/graph-collections/blob/master/src/test/java/org/neo4j/collections/list/TestUnrolledLinkedListConcurrency.java#L66

I am assuming that the writing thread is signalling with read signal (line
158) prior to the reading thread having arrived at its wait point for that
signal (line 129) and therefore the reading thread is stuck waiting for the
read signal, and the writing thread is stuck waiting for the reading thread
to tell it to continue.

I will look into a fix and get it in asap.

Cheers
Bryce

**Comment by brycenz** [comment]
I have merged in a change I have done.  Assuming my thoughts above do match what the actual issue is then this should fix the problem.  Hard to know 100% on this one.
